"""Events module for structured logging."""

from alpacalyzer.events.emitter import (
    CallbackEventHandler,
    ConsoleEventHandler,
    EventEmitter,
    EventHandler,
    FileEventHandler,
    emit_event,
)
from alpacalyzer.events.models import (
    AgentReasoningEvent,
    CooldownEndedEvent,
    CooldownStartedEvent,
    CycleCompleteEvent,
    EntryBlockedEvent,
    EntryTriggeredEvent,
    ErrorEvent,
    ExitTriggeredEvent,
    LLMCallEvent,
    OrderCanceledEvent,
    OrderFilledEvent,
    OrderRejectedEvent,
    OrderSubmittedEvent,
    PositionClosedEvent,
    PositionOpenedEvent,
    ScanCompleteEvent,
    SignalExpiredEvent,
    SignalGeneratedEvent,
    TradingEvent,
)

__all__ = [
    # Event models
    "AgentReasoningEvent",
    "ScanCompleteEvent",
    "SignalGeneratedEvent",
    "SignalExpiredEvent",
    "EntryTriggeredEvent",
    "EntryBlockedEvent",
    "ExitTriggeredEvent",
    "OrderSubmittedEvent",
    "OrderFilledEvent",
    "OrderCanceledEvent",
    "OrderRejectedEvent",
    "PositionOpenedEvent",
    "PositionClosedEvent",
    "CooldownStartedEvent",
    "CooldownEndedEvent",
    "CycleCompleteEvent",
    "LLMCallEvent",
    "ErrorEvent",
    "TradingEvent",
    # Event emitter
    "EventEmitter",
    "EventHandler",
    "ConsoleEventHandler",
    "FileEventHandler",
    "CallbackEventHandler",
    "emit_event",
]
